Repository BC-SECURITY/Empire, pull requests merged in 2020-05, with the labels that each got.

#202 Reflective pe injection fixes
  data/module_source/code_execution/Invoke-ReflectivePEInjection.ps1
  data/module_source/management/Invoke-ReflectivePEInjection.ps1
  lib/common/stagers.py
  lib/modules/powershell/code_execution/invoke_reflectivepeinjection.py
  lib/modules/powershell/management/reflective_inject.py
Labels: bug

#200 Updated Mimikatz to 20200502 TPM, IF & XOR
  data/module_source/credentials/Invoke-Mimikatz.ps1
  lib/modules/powershell/credentials/mimikatz/command.py
Labels: bug, enhancement

#206 Fix for Keylogger module
  lib/common/agents.py
Labels: bug

#211 Mimikatz 2.2.0 20200519 Windows 10 2004 (build 19041)
  data/module_source/credentials/Invoke-Mimikatz.ps1
Labels: enhancement

#207 Changed thunderstruck youtube video URL. Chose a video with no ADs...
  lib/modules/powershell/trollsploit/thunderstruck.py
Labels: bug

#213 Added API endpoints for plugins
  empire
  lib/common/empire.py
  lib/common/modules.py
  plugins/example.py
Labels: enhancement
